services:
  backend-dev:
    build:
      context: .
      dockerfile: ./dogdb-backend/Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development

  frontend-dev:
    build:
      context: .
      dockerfile: ./dogdb-frontend/Dockerfile.dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
