services:
  postgres:
    image: ghcr.io/yaredow/dogdb-postgres:latest
    container_name: dev-postgres
    environment:
      POSTGRES_DB: ${POSTGRESDB_DATABASE}
      POSTGRES_USER: ${POSTGRESDB_USER}
      POSTGRES_PASSWORD: ${POSTGRESDB_ROOT_PASSWORD}
    ports:
      - "5432:5432" # Correctly placed outside of the environment section
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
  pgdata:

networks:
  dev-network:
