ARG NODE_VERSION=20.17.0

FROM node:${NODE_VERSION}-alpine AS build

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /usr/src/app


# Copy the prisma schema and source files
COPY prisma ./prisma

# Copying all the files in our project
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Installing dependencies
RUN npm install

RUN npm run build

# Exposing server port and prisma
EXPOSE 5000
EXPOSE 5555

# Starting our application
CMD [ "npm", "run", "start:migrate:prod" ]


