name: Deploy

on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy images
    runs-on: ubuntu-latest

    steps:
      # Install SSH keys for access
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      # Connect to VPS and deploy images
      - name: Deploy on VPS
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ${{ secrets.WORK_DIR }} &&
          docker-compose pull &&
          docker-compose up -d &&
          exit"

      # Cleanup SSH keys
      - name: Cleanup
        run: rm -rf ~/.ssh
