name: Publish

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ${{ github.actor }}/dogdb-backend:latest
  DB_IMAGE_NAME: ${{ github.actor }}/dogdb-postgres:latest
  FRONTEND_IMAGE_NAME: ${{ github.actor }}/dogdb-frontend:latest

jobs:
  publish:
    name: Publish images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GH_SECRET}}

      - name: Build and Publish Server Image
        uses: docker/build-push-action@v3
        with:
          context: ./dogdb-backend
          file: ./dogdb-backend/Dockerfile.back
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}

      # Build and push database image
      - name: Build and Publish Database Image
        run: |
          docker pull postgres:latest
          docker tag postgres:latest ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}

      # Build and push frontend image
      - name: Build and Publish Frontend Image
        uses: docker/build-push-action@v3
        with:
          context: ./dogdb-frontend/
          file: ./dogdb-frontend/Dockerfile.front
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
