name: Publish

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ${{ github.actor }}/dogdb-backend:latest
  DB_IMAGE_NAME: ${{ github.actor }}/dogdb-postgres:latest
  FRONTEND_IMAGE_NAME: ${{ github.actor }}/dogdb-frontend:latest

jobs:
  publish:
    name: Publish images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GH_SECRET }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin      # Build and push server image

      - name: Build and Publish Server Image
        run: |
          docker build -f ../../dogdb-backend/Dockerfile.back -t ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }} ../../dogdb-backend
          docker push ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}

      # Build and push database image
      - name: Build and Publish Database Image
        run: |
          docker pull postgres:latest
          docker tag postgres:latest ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}

      # Build and push frontend image
      - name: Build and Publish Frontend Image
        run: |
          docker build -f ../../dogdb-frontend/Dockerfile.front -t ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }} ../../dogdb-frontend
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
