name: Publish and Deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: ${{ github.actor }}/dogdb-backend:latest
  DB_IMAGE_NAME: ${{ github.actor }}/dogdb-postgres:latest
  FRONTEND_IMAGE_NAME: ${{ github.actor }}/dogdb-frontend:latest

jobs:
  publish:
    name: Publish images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Log in to GitHub Container Registryy
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.REGISTRY}}
          username: ${{secrets.GH_USER}}
          password: ${{secrets.GH_SECRET}} # Build and push backend image

      - name: Build and Publish Server Image
        uses: docker/build-push-action@v3
        with:
          context: ./dogdb-backend
          file: ./dogdb-backend/Dockerfile.back
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.SERVER_IMAGE_NAME }}

      # Pull and tag postgres image
      - name: Build and Publish Database Image
        run: |
          docker pull postgres:latest
          docker tag postgres:latest ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}

      # Build and push frontend image
      - name: Build and Publish Frontend Image
        uses: docker/build-push-action@v3
        with:
          context: ./dogdb-frontend/
          file: ./dogdb-frontend/Dockerfile.front
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Using the private key for authentication
          port: 22
          script: |
            cd ${{ secrets.WORK_DIR }} 
            sudo docker compose pull
            sudo docker compose up -d
